// Ginger Code — Protected Neovim Core
// The protected core contains only what Ginger needs:
// RPC bridge, workspace hooks, buffer/selection/diagnostics events,
// Action invocation, package activation, session lifecycle, required commands.
//
// This is generated as a Lua file and loaded before user config.

pub const PROTECTED_CORE_LUA: &str = r#"
-- Ginger Code Protected Core v0.1
-- DO NOT EDIT — this file is generated by Ginger Code
-- User customization goes in ~/.ginger/init.lua or workspace .ginger/init.lua

local M = {}

-- Ginger RPC bridge — exposes functions for Ginger to call from Rust
function M.setup(opts)
  opts = opts or {}

  -- Register Ginger commands
  vim.api.nvim_create_user_command("GingerAction", function(args)
    -- Invoked by Ginger via RPC to trigger an action
    vim.rpcnotify(opts.channel, "ginger_action", { action = args.args })
  end, { nargs = 1 })

  vim.api.nvim_create_user_command("GingerState", function(args)
    vim.rpcnotify(opts.channel, "ginger_state", { state = args.args })
  end, { nargs = 1 })

  -- Buffer events — notify Ginger
  local group = vim.api.nvim_create_augroup("GingerCore", { clear = true })

  vim.api.nvim_create_autocmd("BufEnter", {
    group = group,
    callback = function(ev)
      vim.rpcnotify(opts.channel, "ginger_buffer_enter", {
        buf = ev.buf,
        file = ev.file,
      })
    end,
  })

  vim.api.nvim_create_autocmd("BufWritePost", {
    group = group,
    callback = function(ev)
      vim.rpcnotify(opts.channel, "ginger_buffer_save", {
        buf = ev.buf,
        file = ev.file,
      })
    end,
  })

  vim.api.nvim_create_autocmd("CursorMoved", {
    group = group,
    callback = function(ev)
      local pos = vim.api.nvim_win_get_cursor(0)
      vim.rpcnotify(opts.channel, "ginger_cursor_moved", {
        buf = ev.buf,
        row = pos[1],
        col = pos[2],
      })
    end,
  })

  vim.api.nvim_create_autocmd("DiagnosticChanged", {
    group = group,
    callback = function(ev)
      local diagnostics = vim.diagnostic.get(ev.buf)
      vim.rpcnotify(opts.channel, "ginger_diagnostics", {
        buf = ev.buf,
        count = #diagnostics,
      })
    end,
  })

  -- Session lifecycle
  vim.api.nvim_create_autocmd("VimLeavePre", {
    group = group,
    callback = function()
      vim.rpcnotify(opts.channel, "ginger_exit", {})
    end,
  })

  M.channel = opts.channel
  vim.g.ginger_ready = 1
end

return M
"#;

/// Generate the protected core Lua file path for a workspace.
pub fn protected_core_path(data_root: &std::path::Path) -> std::path::PathBuf {
    data_root.join("core").join("protected_init.lua")
}

/// Write the protected core Lua file if it doesn't exist.
pub fn ensure_protected_core(data_root: &std::path::Path) -> std::io::Result<()> {
    let path = protected_core_path(data_root);
    if path.exists() {
        return Ok(());
    }
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(&path, PROTECTED_CORE_LUA)?;
    tracing::info!("Protected core written: {}", path.display());
    Ok(())
}

/// Generate a workspace-specific Neovim init that loads protected core + user config.
pub fn generate_workspace_config(
    data_root: &std::path::Path,
    workspace_root: &std::path::Path,
    channel: u64,
) -> std::io::Result<std::path::PathBuf> {
    let config_dir = data_root.join("core");
    std::fs::create_dir_all(&config_dir)?;

    let config_path = config_dir.join("workspace_init.lua");
    let protected = protected_core_path(data_root);
    let user_workspace = workspace_root.join(".ginger").join("init.lua");
    let user_global = dirs::home_dir()
        .map(|h| h.join(".ginger").join("init.lua"))
        .unwrap_or_default();

    let mut content = format!(
        "-- Ginger Code workspace config (generated, do not edit)\n"
        "-- Channel: {channel}\n\n"
        "local channel = {channel}\n\n"
    );

    // Protected core
    content.push_str(&format!(
        "local ok, core = pcall(require, \"{}\")\n"
        "if ok then core.setup({{ channel = channel }}) end\n\n",
        protected.with_extension("").display()
    ));

    // User global config
    if user_global.exists() {
        content.push_str(&format!(
            "pcall(dofile, \"{}\")\n\n",
            user_global.display()
        ));
    }

    // User workspace config
    if user_workspace.exists() {
        content.push_str(&format!(
            "pcall(dofile, \"{}\")\n\n",
            user_workspace.display()
        ));
    }

    std::fs::write(&config_path, content)?;
    tracing::info!("Workspace config generated: {}", config_path.display());
    Ok(config_path)
}